import { Media } from '@/types';

export const mockMedia: Media[] = [
    // Audio - Telugu Songs
    {
        id: 'audio-1',
        title: 'Butta Bomma',
        type: 'audio',
        artist: 'Armaan Malik',
        artistId: 'artist-1',
        genre: 'Romantic',
        category: 'Telugu',
        duration: 245,
        thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400',
        url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
        views: 15420,
        uploadedBy: '1',
        uploadedAt: '2024-01-15T10:00:00Z',
        status: 'approved',
        description: 'Romantic melody from Ala Vaikunthapurramuloo',
        musicDirector: 'Thaman S',
        singer: 'Armaan Malik',
        movie: 'Ala Vaikunthapurramuloo',
    },
    {
        id: 'audio-2',
        title: 'Samajavaragamana',
        type: 'audio',
        artist: 'Sid Sriram',
        artistId: 'artist-2',
        genre: 'Romantic',
        category: 'Telugu',
        duration: 268,
        thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
        url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
        views: 23100,
        uploadedBy: '1',
        uploadedAt: '2024-01-20T10:00:00Z',
        status: 'approved',
        description: 'Soulful melody from Ala Vaikunthapurramuloo',
        musicDirector: 'Thaman S',
        singer: 'Sid Sriram',
        movie: 'Ala Vaikunthapurramuloo',
    },
    {
        id: 'audio-3',
        title: 'Inkem Inkem',
        type: 'audio',
        artist: 'Sid Sriram',
        artistId: 'artist-2',
        genre: 'Romantic',
        category: 'Telugu',
        duration: 312,
        thumbnail: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400',
        url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
        views: 18900,
        uploadedBy: '1',
        uploadedAt: '2024-02-01T10:00:00Z',
        status: 'approved',
        description: 'Beautiful love song from Geetha Govindam',
        musicDirector: 'Gopi Sundar',
        singer: 'Sid Sriram',
        movie: 'Geetha Govindam',
    },
    // Audio - Hindi Songs
    {
        id: 'audio-4',
        title: 'Tum Hi Ho',
        type: 'audio',
        artist: 'Arijit Singh',
        artistId: 'artist-3',
        genre: 'Romantic',
        category: 'Hindi',
        duration: 262,
        thumbnail: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400',
        url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
        views: 45200,
        uploadedBy: '1',
        uploadedAt: '2024-01-10T10:00:00Z',
        status: 'approved',
        description: 'Iconic romantic song from Aashiqui 2',
        musicDirector: 'Mithoon',
        singer: 'Arijit Singh',
        movie: 'Aashiqui 2',
    },
    {
        id: 'audio-5',
        title: 'Kesariya',
        type: 'audio',
        artist: 'Arijit Singh',
        artistId: 'artist-3',
        genre: 'Romantic',
        category: 'Hindi',
        duration: 278,
        thumbnail: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400',
        url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
        views: 52300,
        uploadedBy: '1',
        uploadedAt: '2024-01-25T10:00:00Z',
        status: 'approved',
        description: 'Melodious track from Brahmastra',
        musicDirector: 'Pritam',
        singer: 'Arijit Singh',
        movie: 'Brahmastra',
    },
    // Video - Music Videos
    {
        id: 'video-1',
        title: 'Naatu Naatu',
        type: 'video',
        artist: 'Rahul Sipligunj, Kaala Bhairava',
        artistId: 'artist-4',
        genre: 'Dance',
        category: 'Telugu',
        duration: 295,
        thumbnail: 'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=400',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        views: 89500,
        uploadedBy: '1',
        uploadedAt: '2024-01-05T10:00:00Z',
        status: 'approved',
        description: 'Oscar-winning song from RRR',
        musicDirector: 'M. M. Keeravani',
        singer: 'Rahul Sipligunj, Kaala Bhairava',
        movie: 'RRR',
    },
    {
        id: 'video-2',
        title: 'Oo Antava',
        type: 'video',
        artist: 'Indravathi Chauhan',
        artistId: 'artist-5',
        genre: 'Item Song',
        category: 'Telugu',
        duration: 248,
        thumbnail: 'https://images.unsplash.com/photo-1574169208507-84376144848b?w=400',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        views: 67800,
        uploadedBy: '1',
        uploadedAt: '2024-01-12T10:00:00Z',
        status: 'approved',
        description: 'Chartbuster from Pushpa',
        musicDirector: 'Devi Sri Prasad',
        singer: 'Indravathi Chauhan',
        movie: 'Pushpa',
    },
    // Pending uploads
    {
        id: 'audio-pending-1',
        title: 'New Romantic Song',
        type: 'audio',
        artist: 'New Artist',
        artistId: 'artist-6',
        genre: 'Romantic',
        category: 'Telugu',
        duration: 240,
        thumbnail: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400',
        url: '',
        views: 0,
        uploadedBy: '3',
        uploadedAt: '2024-02-10T10:00:00Z',
        status: 'pending',
        description: 'Awaiting moderation',
    },
];

export const genres = [
    'Romantic',
    'Dance',
    'Item Song',
    'Devotional',
    'Classical',
    'Folk',
    'Party',
    'Sad',
];

export const categories = [
    'Telugu',
    'Hindi',
    'Tamil',
    'Kannada',
    'Malayalam',
    'English',
];

export const artists = [
    { id: 'artist-1', name: 'Armaan Malik', image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Armaan' },
    { id: 'artist-2', name: 'Sid Sriram', image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sid' },
    { id: 'artist-3', name: 'Arijit Singh', image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arijit' },
    { id: 'artist-4', name: 'Rahul Sipligunj', image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul' },
    { id: 'artist-5', name: 'Indravathi Chauhan', image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Indravathi' },
];
